POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "email": "kayraparlak@gmail.com",
    "password": "123456"
}

###

POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email": "kayraparlak@gmail.com",
    "password": "123456"
}

###

POST http://localhost:3001/chat/newChat
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTMxZjUxYWYzMjQ5OTVkYWFmZDcwZCIsImlhdCI6MTc0MDk5MDgxNX0.Xoojh3heaPg8uKoFv3dTH2HIbYcLSj89CfNLy7UOU5E


###

GET http://localhost:3001/chat?chatUrl=da8db0ac0fb17c636f864a149dbc793e8db2998d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTMxZjUxYWYzMjQ5OTVkYWFmZDcwZCIsImlhdCI6MTc0MDk5MDgxNX0.Xoojh3heaPg8uKoFv3dTH2HIbYcLSj89CfNLy7UOU5E


###
POST http://localhost:3001/chat
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTMxZjUxYWYzMjQ5OTVkYWFmZDcwZCIsImlhdCI6MTc0MDk5MDgxNX0.Xoojh3heaPg8uKoFv3dTH2HIbYcLSj89CfNLy7UOU5E
Content-Type: application/json

{
    "chatUrl": "71c7f35752397674ed15585a750340d32be6018e",
    "userMessage": "Merhaba Bugün günlerden ne? Bana Bunu söyler misin?",
    "version":"claude-3-5-haiku-20241022"
}